# Generated by Django 6.0.2 on 2026-02-06 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("musical", "Musical"),
                            ("dance", "Dance"),
                            ("art", "Art"),
                            ("shop", "Shop"),
                            ("service", "Service"),
                        ],
                        max_length=50,
                    ),
                ),
                ("icon_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="HostProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField()),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.category",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("event", "Event"), ("service", "Service")],
                        max_length=10,
                    ),
                ),
                ("latitude", models.FloatField(help_text="Latitude for map pin")),
                ("longitude", models.FloatField(help_text="Longitude for map pin")),
                ("address", models.CharField(max_length=255)),
                ("event_date", models.DateTimeField(blank=True, null=True)),
                ("booking_link", models.URLField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="listings/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="api.hostprofile",
                    ),
                ),
            ],
        ),
    ]
