# Generated by Django 6.0.2 on 2026-02-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_hostprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon_url",
            field=models.CharField(blank=True),
        ),
    ]
