# Generated by Django 6.0.2 on 2026-02-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_category_icon_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostprofile",
            name="category",
        ),
        migrations.AlterField(
            model_name="listing",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Latitude for map pin", null=True
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Longitude for map pin", null=True
            ),
        ),
    ]
