# Generated by Django 6.0.2 on 2026-02-07 05:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_hostprofile_category_alter_listing_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon_url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="hostprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
