# Generated by Django 6.0.2 on 2026-02-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_category_icon_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
    ]
